logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %5p --- %-40.40logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
    file: "%d{HH:mm:ss.SSS} %5p --- %-40.40logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  file:
    name: log/practical-java.log

spring:
  main:
    banner-mode: OFF

server:
  port: 8001